# Generated by Django 2.2.4 on 2019-08-09 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=120, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=120, verbose_name='Apellidos')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo')),
                ('fecha_de_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('lugar_origen', models.CharField(max_length=120)),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
