# Generated by Django 2.2.4 on 2019-08-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waypoint',
            name='neighbor_waypoints',
            field=models.ManyToManyField(blank=True, through='api.Route', to='api.Waypoint'),
        ),
    ]
